#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION "2018.3.0b12"
#define UNITY_VERSION_DIGITS "2018.3.0"
#define UNITY_VERSION_SUFFIX "b12"
#define UNITY_VERSION_VER 2018
#define UNITY_VERSION_MAJ 3
#define UNITY_VERSION_MIN 0
#define UNITY_IS_BETA 1
