#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2018.3.0b12_77f6238a7ced"
#define UNITY_VERSION_FULL_NICE "2018.3.0b12 (77f6238a7ced)"
#define UNITY_VERSION_BLD 7861795
#define UNITY_VERSION_DATE 1542873419
#define UNITY_VERSION_WIN "2018.3.0.7861795"
#define UNITY_VERSION_BRANCH "2018.3/staging"
